// Code generated by hertz generator.

package main

import (
	"chenyucms/app/http/controllers"
	handler "chenyucms/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	// module plugin router ...
	m := r.Group("/module")
	{
		m.Any("/:mod/:serv", handler.Module)
	}
	r.GET("/hello", handler.Hello)
	// Swagger
	r.GET("/test", controllers.Test)

}
